### ReplicaSet configuration
replicaCount:
  frontend: 2
  backend: 2

### NLWeb configuration
neoload:
  configuration:
    # The secret key must be at least 8 characters long
    secretKey: YOUR_CUSTOM_SECRET_KEY
    backend:
      mongo:
        host: YOUR_MONGODB_HOST_URL
        port: 27017
      # Enable licensing features (VUHs) by setting this token, or leave it empty
      licensingPlatformToken:

### MongoDB user configuration
mongodb:
  usePassword: true
  mongodbUsername: YOUR_MONGODB_USER
  mongodbPassword: YOUR_MONGODB_PASSWORD

### Services host configuration
services:
  webapp:
    host: neoload-web.mycompany.com
  api:
    host: neoload-web-api.mycompany.com
  files:
    host: neoload-web-files.mycompany.com

### Ingress configuration
### Choose your preferred ingress controller configuration
ingress:
  enabled: true
  # Replace these annotations accordingly if you are not using the openshift ingress controller
  annotations:
    haproxy.router.openshift.io/rewrite-target: "/"
    route.openshift.io/termination: "edge"

  ### TLS configuration
  ### Uncomment if you want to secure your app with https
#  tls:
#    - secretName: tls-secret
#      secretCertificate: |-
#        -----BEGIN CERTIFICATE-----
#        YOUR_CERTIFICATE
#        -----END CERTIFICATE-----
#      secretKey: |-
#        -----BEGIN PRIVATE KEY-----
#        YOUR_PRIVATE_KEY
#        -----END PRIVATE KEY-----
