{{- if eq (include "nlweb.ha.mode" .) "API" -}}
{{- if .Values.clusterRbac.enabled -}}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-hazelcast-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: {{ include "nlweb.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-hazelcast-cluster-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}