apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nlweb.fullname" . }}-licensing-secret
  namespace: {{ .Release.Namespace }}  
  labels:
    {{- include "nlweb.labels" . | nindent 4 }}
type: Opaque
data:
  licensingPlatformToken: {{ .Values.neoload.configuration.licensingPlatformToken | toString | b64enc | quote }}