{{- if .Values.mongodb -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nlweb.fullname" . }}-mongo-secret
  namespace: {{ .Release.Namespace }}  
  labels:
    {{- include "nlweb.labels" . | nindent 4 }}
type: Opaque
data:
  host: {{ .Values.neoload.configuration.backend.mongo.host | required "MongoDb host (--set neoload.configuration.backend.mongo.host=YOUR_MONGODB_HOST) value is required." | b64enc | quote }}
  {{- if .Values.mongodb.usePassword -}}
  username: {{ .Values.mongodb.mongodbUsername | required "You need to specify a MongoDB username. (--set mongodb.mongodbUsername=user)" | b64enc | quote }}
  password: {{ .Values.mongodb.mongodbPassword | required "You need to specify a MongoDB password. (--set mongodb.mongodbPassword=password)" | b64enc | quote }}
  {{- end -}}
{{- end -}}